apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Define namespace padrão para todos os resources desta composição
namespace: n8n

resources:
  - namespace.yaml
  - secrets.yaml
  - hpa.yaml
  - postgres        # diretório com kustomization.yaml próprio
  - redis           # diretório com kustomization.yaml próprio
  - n8n             # base do app (já inclui ingress.yaml via n8n/kustomization.yaml)

