apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n
  namespace: n8n
  annotations:
    # Diz ao cert-manager para emitir/renovar certificado Let's Encrypt
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  # Garante que o Traefik (padrão do K3s) controle este Ingress
  ingressClassName: traefik

  # TLS: cert-manager criará/atualizará este Secret automaticamente
  tls:
    - hosts:
        - n8n.129-213-28-76.sslip.io
      secretName: n8n-tls

  rules:
    - host: n8n.129-213-28-76.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 5678
