
# n8n/kustomization.yaml
resources:
  - main-statefulset.yaml
  - workers-deployment.yaml
  - service-headless.yaml
  - service-web.yaml
  - pvc.yaml
  - ingress.yaml

images:
  - name: n8nio/n8n
    newTag: "1.117.3"

