
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Use o StatefulSet base (vamos torná-lo stateless via patch)
  - main-statefulset.yaml

  # Serviços e Ingress continuam
  - service-web.yaml
  # Se não precisa de headless, pode remover a linha abaixo
  # - service-headless.yaml
  - ingress.yaml

images:
  - name: n8nio/n8n
    newTag: "1.123.6"

